// EdgeCommons v1.0.4 +++ Visit edgecommons.org for documentation, updates and examples +++ Copyright (c) 2013 by Simon Widjaja +++ Distributed under the terms of the MIT license (http://www.opensource.org/licenses/mit-license.html) +++ This notice shall be included in all copies or substantial portions of the Software.
// Input 0
(function(a,d){var c=function(){};c.VERSION="0.0.2";c.$=d;a.Modulog=c})(window,jQuery);
(function(){var a=function(){};a.VERSION="0.0.2";a.LEVEL_NONE=0;a.LEVEL_ERROR=1;a.LEVEL_WARN=2;a.LEVEL_INFO=3;a.LEVEL_DEBUG=4;a.level=a.LEVEL_DEBUG;var d=null;a.addLogTarget=function(c){"function"===typeof c&&(d=c)};a.debug=function(c,a,b){ModulogLog.level>=ModulogLog.LEVEL_DEBUG&&(c="[ DEBUG "+(a?"| "+a+" ":"")+"] "+c,"undefined"!=typeof console&&"undefined"!=typeof console.debug?b?console.debug(c,b):console.debug(c):"undefined"!=typeof console&&"undefined"!=typeof console.info&&(b?console.info(c,
b):console.info(c)),ModulogLog.__delegate(c,b))};a.info=function(c,a,b){ModulogLog.level>=ModulogLog.LEVEL_INFO&&(c="[ INFO "+(a?"| "+a+" ":"")+"] "+c,"undefined"!=typeof console&&"undefined"!=typeof console.info&&(b?console.info(c,b):console.info(c)),ModulogLog.__delegate(c,b))};a.warn=function(a,e,b){ModulogLog.level>=ModulogLog.LEVEL_WARN&&(a="[ WARN "+(e?"| "+e+" ":"")+"] "+a,"undefined"!=typeof console&&"undefined"!=typeof console.warn&&(b?console.warn(a,b):console.warn(a)),ModulogLog.__delegate(a,
b))};a.error=function(a,e,b){ModulogLog.level>=ModulogLog.LEVEL_ERROR&&(a="[ ERROR "+(e?"| "+e+" ":"")+"] "+a,"undefined"!=typeof console&&"undefined"!=typeof console.error&&(b?console.error(a,b):console.error(a)),ModulogLog.__delegate(a,b))};a.__delegate=function(a,e){d&&(e?d(a+" : "+e.toString()):d(a))};window.Log=window.MLog=window.ModulogLog=a})(window.Modulog);
(function(a){var d=function(){};d.VERSION="0.0.1";var c=a.$,e=null,b=ModulogLog;d.get=function(a){for(var c=a.split("."),f=e,j=0;j<c.length;j++){var b=c[j];f.hasOwnProperty(b)||ModulogLog.warn("Config value not found: "+a,"CONFIG");f=f[b]}return f};d.set=function(a,c){for(var f=a.split("."),j=e,b=0;b<f.length-1;b++)j=j[f[b]];j[f.pop()]=c};d.init=function(a,d){"string"===typeof a&&jQuery?c.getJSON(a,function(a){e=a;"function"===typeof d&&d()}):"object"===typeof a?e=a:b.error("Could not init config. init() function expects config object or url to config.js. Latter needs jQuery to be initialized before.",
"Modulog | ModulogConfig")};window.Config=window.MConfig=window.ModulogConfig=d})(window.Modulog);
// Input 1
(function(a,d){var c=function(){};c.VERSION="1.0.4";c.$=d;a.EC=a.EdgeCommons=c})(window,jQuery);
// Input 2
(function(a){var d=function(){};d.VERSION="1.1.0";var c=a.$,e=ModulogLog,b=null,l=null,i=null;a.getSymbolName=function(a,c){var b=a.getVariable("symbolSelector");if(!c){var e=a.getParentSymbol();e&&(b=b.replace(e.getVariable("symbolSelector")+"_",""))}return b=b.replace("#","")};a.getInjectedData=function(a,b){try{b=b||"data";for((!a||!a.getParentSymbol)&&e.error("getInjectedData(): First argument 'sys' is not optional","EdgeCommons | Core");a.getParentSymbol();)a=a.getParentSymbol();var d=a.getSymbolElement().find("."+
b).html();return c.parseJSON(d)}catch(g){e.error("Reading injected data failed (scriptClassSelector="+b+")","EdgeCommons | Core",g)}};a.setAdaptiveLayouts=function(f,d,m,g){!f||!f.length?e.error("Error in setAdaptiveLayouts(). Argument 'layouts' is not optional and has to be an array.","EdgeCommons | Core"):(b=f,d&&("function"==typeof g&&(i=g),c(window).resize(function(){a.applyAdaptiveLayout(d,m)}),a.applyAdaptiveLayout(d,m)))};a.applyAdaptiveLayout=function(a,e){try{a.setVariable("doResizing",function(){var d=
a.getComposition().getStage().getSymbolElement().width(),k=a.$(e),h=null;c.each(b,function(a,b){d>=b-0&&(h=b)});l!=h&&(l=h,k.html(""),k=a.createChildSymbol("layout"+h,e),"function"==typeof i&&i(h,k));a.$("currentLayout").html(a.getVariable("layout"))}),a.getVariable("doResizing")()}catch(d){console.error(d)}};a.centerStage=function(a){a?a.getComposition().getStage().getSymbolElement().css("margin","0px auto"):e.error("Error in centerStage(). Argument 'sym' is not optional.","EdgeCommons | Core")};
a.loadComposition=function(b,c){if(!b||!c)e.error("Error in loadComposition(). Arguments 'src' and 'sym' are not optional.","EdgeCommons | Core");else{try{var d;d=c instanceof AdobeEdge.Symbol?c.getSymbolElement():c;var g="ec_"+Math.random().toString(36).substring(7);d.html('<iframe id="'+g+'" src="'+b+'" style="overflow: hidden; width: 100%; height: 100%; margin: auto; border: 0 none; background-color: rgba(255,255,255,0)"></iframe>');var k=new jQuery.Deferred,h=jQuery("#"+g),i=h[0].contentWindow;
h.load(function(){i.AdobeEdge.bootstrapCallback(function(a){a=i.AdobeEdge.getComposition(a);k.resolve(a,g,i.AdobeEdge)})})}catch(l){a.error("Error in loadComposition: ","EdgeCommons | Core",l.toString())}return k}};a.Core=d;a.Log=e;a.debug=e.debug;a.info=e.info;a.warn=e.warn;a.error=e.error;a.Config=MConfig})(EdgeCommons);
